Workaround for undefined reference to sem_* functions
Should really fix this in the build system to add -pthread when
necessary instead of setting an env var

Workaround for #7